"""
Activity Tier Comparison — Top 10% vs Bottom 10% by session count.

Loads tier seed files (generated by MCP query, since the anon REST key
cannot filter on the TEXT-typed total_sessions column) and runs the full
hybrid pipeline on each group, then prints a side-by-side fill rate and
score distribution report.

Seed files (50 companies each, pre-populated):
  results/tier_top_50.json     — top 10% by sessions (>= 1,295)
  results/tier_bottom_50.json  — bottom 10% by sessions (<= 2)

Usage:
  python3 run_activity_tiers.py          # runs both tiers (50 each)
"""

import asyncio
import json
import os
import sys
from datetime import datetime

import aiohttp

sys.path.insert(0, os.path.dirname(__file__))
from run_hybrid_pipeline import run_pipeline, SUPABASE_URL, SUPABASE_KEY

TOP_SEED_PATH    = "results/tier_top_50.json"
BOTTOM_SEED_PATH = "results/tier_bottom_50.json"

ICP_FIELDS = [
    "sf_is_public",
    "sf_funding_stage",
    "sf_employee_range",
    "si_recent_funding",
    "si_recent_publications",
    "si_patent_filings",
    "sm_active_med_chem",
    "sm_cadd_capabilities",
    "sm_hit_to_lead",
    "sm_virtual_screening",
]


def load_tier(path: str) -> list:
    with open(path) as f:
        rows = json.load(f)
    return [
        {
            "domain":         r["domain"],
            "user_count":     r.get("user_count", 1),
            "total_sessions": r.get("total_sessions", 1),
            "last_active":    r.get("last_active"),
        }
        for r in rows
    ]


_EMPTY_PATTERNS = (
    "unknown", "not found", "no ", "none ", "n/a", "not applicable",
    "no evidence", "not available", "could not", "unable to", "not public",
    "not a public", "not listed", "not in ", "no data", "not confirmed",
    "lookup failed", "treat as unknown", "not checked",
)

def is_real_fill(value) -> bool:
    """True only if the value contains actual confirmed evidence (positive or negative from a source)."""
    if value in (None, "", "null"):
        return False
    v = str(value).strip().lower()
    if not v:
        return False
    # Reject vague non-answers
    if any(v.startswith(p) or p in v[:60] for p in _EMPTY_PATTERNS):
        return False
    return True


def print_fill_rates(results: list, label: str) -> dict:
    total = len(results)
    rates = {}
    print(f"\n{'='*55}")
    print(f"FILL RATES — {label} ({total} companies)")
    print(f"{'='*55}")
    print(f"{'Field':<30} {'Filled':>8} {'%':>6}")
    print("-"*46)
    for field in ICP_FIELDS:
        filled = sum(1 for r in results if is_real_fill(r.get(field)))
        pct = round(filled / total * 100) if total else 0
        rates[field] = pct
        print(f"{field:<30} {filled:>5}/{total:<3} {pct:>5}%")
    return rates


def print_score_distribution(results: list, label: str) -> dict:
    total = len(results)
    counts = {"HIGH FIT": 0, "MEDIUM FIT": 0, "LOW FIT": 0, "NO FIT": 0, "ERROR": 0}
    scores = [r.get("final_icp_score") for r in results if r.get("final_icp_score") is not None]
    for r in results:
        status = r.get("qualification_status", "ERROR")
        counts[status] = counts.get(status, 0) + 1

    print(f"\n{'='*55}")
    print(f"ICP DISTRIBUTION — {label} ({total} companies)")
    print(f"{'='*55}")
    for status, n in counts.items():
        if n:
            pct = round(n / total * 100)
            print(f"  {status:<15} {n:>4} ({pct}%)")
    if scores:
        avg = round(sum(scores) / len(scores), 1)
        print(f"  Avg score:     {avg}/100  (n={len(scores)})")
    return {"distribution": counts, "avg_score": round(sum(scores) / len(scores), 1) if scores else None}


def print_comparison(top_rates: dict, bottom_rates: dict):
    print(f"\n{'='*65}")
    print("FILL RATE COMPARISON — TOP 10% vs BOTTOM 10%")
    print(f"{'='*65}")
    print(f"{'Field':<30} {'TOP 10%':>8} {'BOT 10%':>8} {'DELTA':>7}")
    print("-"*55)
    for field in ICP_FIELDS:
        t = top_rates.get(field, 0)
        b = bottom_rates.get(field, 0)
        delta = t - b
        arrow = "▲" if delta > 0 else ("▼" if delta < 0 else " ")
        print(f"{field:<30} {t:>7}%  {b:>7}%  {arrow}{abs(delta):>5}%")


async def main():
    print(f"\n{'='*65}")
    print("ACTIVITY TIER COMPARISON")
    print(f"{'='*65}\n")

    print(f"Loading top 10% tier from {TOP_SEED_PATH}...")
    top_companies = load_tier(TOP_SEED_PATH)
    print(f"  {len(top_companies)} companies loaded")

    print(f"Loading bottom 10% tier from {BOTTOM_SEED_PATH}...")
    bottom_companies = load_tier(BOTTOM_SEED_PATH)
    print(f"  {len(bottom_companies)} companies loaded\n")

    print(f"Running ICP pipeline on TOP tier ({len(top_companies)} companies)...")
    async with aiohttp.ClientSession() as session:
        top_results = await run_pipeline(top_companies, session)

    print(f"\nRunning ICP pipeline on BOTTOM tier ({len(bottom_companies)} companies)...")
    async with aiohttp.ClientSession() as session:
        bottom_results = await run_pipeline(bottom_companies, session)

    top_rates    = print_fill_rates(top_results, "TOP 10%")
    bottom_rates = print_fill_rates(bottom_results, "BOTTOM 10%")
    print_comparison(top_rates, bottom_rates)
    top_dist    = print_score_distribution(top_results, "TOP 10%")
    bottom_dist = print_score_distribution(bottom_results, "BOTTOM 10%")

    # Save
    os.makedirs("results", exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    out = {
        "run_at": datetime.now().isoformat(),
        "top_tier": {
            "threshold": ">= 1295 sessions",
            "company_count": len(top_results),
            "fill_rates": top_rates,
            "distribution": top_dist,
            "results": top_results,
        },
        "bottom_tier": {
            "threshold": "<= 2 sessions",
            "company_count": len(bottom_results),
            "fill_rates": bottom_rates,
            "distribution": bottom_dist,
            "results": bottom_results,
        },
    }
    path = f"results/tier_comparison_{ts}.json"
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nResults saved to {path}")


if __name__ == "__main__":
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("ERROR: Set SUPABASE_URL and SUPABASE_KEY in .env")
        sys.exit(1)

    asyncio.run(main())
